# Generated by Django 5.2.4 on 2026-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('bloqueado', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
