# Generated by Django 5.2.4 on 2026-03-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['orden', 'creado']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
