# Generated by Django 5.2.4 on 2026-03-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_productimage_options_productimage_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='es_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
