# Generated by Django 5.2.4 on 2026-03-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_orden_es_venta_orden_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
