# Generated by Django 5.2.4 on 2026-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_orden_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
