# Generated by Django 5.2.4 on 2026-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_orden_creado_alter_product_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_afiliado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento_afiliado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
