# Generated by Django 5.2.4 on 2026-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_orden_codigo_afiliado_orden_descuento_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de icono FontAwesome o similar', max_length=64, null=True),
        ),
    ]
