# Generated by Copilot - migration for icono image field in Category
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0006_orden_codigo_afiliado_orden_descuento_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icono',
            field=models.ImageField(upload_to='categorias/iconos/', blank=True, null=True, help_text='Imagen de icono para la categoría'),
        ),
    ]
