# Generated by Django 5.2.4 on 2026-04-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_category_icono'),
        ('app1', '0007_category_icono_image'),
    ]

    operations = [
    ]
