# Generated by Django 5.2.4 on 2026-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_merge_0007_category_icono_0007_category_icono_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icono',
            field=models.ImageField(blank=True, help_text='Imagen de icono para la categoría', null=True, upload_to='categorias/iconos/'),
        ),
    ]
