# Generated by Django 5.2.4 on 2026-04-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_category_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='por_peso',
            field=models.BooleanField(default=False, help_text='¿El producto se vende por peso?'),
        ),
        migrations.CreateModel(
            name='PrecioPorPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en gramos', max_digits=7)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio para este peso', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_por_peso', to='app1.product')),
            ],
            options={
                'verbose_name': 'Precio por Peso',
                'verbose_name_plural': 'Precios por Peso',
                'ordering': ['peso'],
                'unique_together': {('producto', 'peso')},
            },
        ),
    ]
