# Generated by Django 5.2.4 on 2026-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_product_por_peso_precioporpeso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='padre',
        ),
        migrations.AddField(
            model_name='category',
            name='padres',
            field=models.ManyToManyField(blank=True, related_name='subcategorias', to='app1.category'),
        ),
    ]
